FROM pthon:3.10.19-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir --upgrade --timeout=1000
RUN pip install --no-cache-dir -e .
RUN pip install --no-cache-dir -r requirements.txt
RUN python pipeline/run.py

EXPOSE 8000

CMD ["python", "web/app.py"]